baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Nihaan Arts!'
theme = 'beautifulhugo'


[Params]
  homeTitle = "Nihaan's Art Site !" 
  subtitle = "Welcome to my Art Site ğŸ‘‹!"
  logo = "img/profile.jpg"
  favicon = "img/favicon.ico"


[Author]
    name = 'Nihan'



[[menu.main]]
    name = "ğŸ¡ home"
    url = ""
    weight = 1

[[menu.main]]
    name = "ğŸ˜ About"
    url = "page/aboutme"
    weight = 3


[[menu.main]]
    name = "ğŸ˜‹ My Arts!"
    url = "page/arts"
    weight = 3
